export const branchNames = [
  { id: 1, name: "B.Com" },
  { id: 2, name: "B.A" },
  { id: 3, name: "B.Arch" },
  { id: 4, name: "B.Com.(Hons)" },
  { id: 5, name: "B.Pharmacy" },
  { id: 6, name: "B.Sc - VC" },
  { id: 7, name: "B.Sc (Animation & Gaming)" },
  { id: 8, name: "B.Sc (Hons.) Agriculture" },
  { id: 9, name: "B.Tech AI&DS" },
  { id: 10, name: "B.Tech CS&IT" },
  { id: 11, name: "B.Tech ECS" },
  { id: 12, name: "B.Tech IOT" },
  { id: 13, name: "BBA" },
  { id: 14, name: "BBA- BA" },
  { id: 15, name: "BBA-LLB" },
  { id: 16, name: "BCA" },
  { id: 17, name: "B.Tech ECE" },
  { id: 18, name: "B.Tech CSE - Regular" },
  { id: 19, name: "B.Tech CSE - Honors" },
  { id: 20, name: "B.Tech BT" },
  { id: 21, name: "B.Tech CE" },
  { id: 22, name: "B.Tech EEE" },
  { id: 23, name: "B.Tech ME" },
  { id: 24, name: "LLB" },
  { id: 25, name: "M.Pharmacy" },
  { id: 26, name: "M.Sc Computational Mathematics" },
  { id: 27, name: "M.Sc Nano Science and Technology" },
  { id: 28, name: "M.Sc Chemistry" },
  { id: 29, name: "M.Sc Physics" },
  { id: 30, name: "M.Tech - EVT" },
  { id: 31, name: "M.Tech - PE & PS" },
  { id: 32, name: "MA DH&LS" },
  { id: 33, name: "MA - English" },
  { id: 34, name: "MBA" },
  { id: 35, name: "MCA" },
  { id: 36, name: "M.Sc - F&C" },
  { id: 37, name: "M.Tech - CTM" },
  { id: 38, name: "M.Tech - Machine Design" },
  { id: 39, name: "M.Tech - SE" },
  { id: 40, name: "M.Tech - Thermal Engineering" },
  { id: 41, name: "M.Tech - CSE" },
  { id: 42, name: "Pharma D" },
];
